### ISSUE TITLE
Investigate using SDL/SDL_mixer for audio output

### ISSUE THREAD

**Issue by wolfbeast** [MoonchildProductions/moebius#114]
Following an IRC discussion where this was suggested as an alternative to trying to support multiple cubeb back-ends (ALSA/Pulse/JACK/WMF/DX/etc.), we should have a look at SDL as an alternative library to handle all of the platform's audio needs.

- O.S. support?
- dependency requirements?
- Licensing?
- Integration with complex streaming formats like MSE?

etc.

**Comment by calimeroteknik** [comment]
**Licensing:**
SDL2 uses the zlib license, which is even more permissive than LGPL (which SDL1 used), and approved by the FSF as a free software license. The main reason SDL switched to zlib licensing is to allow proprietary games to embed it at compile-time. I think this point should go smoothly.

**Platform support:**
Linux:  OSS, ALSA (and see sound servers)
FreeBSD:  OSS (and see sound servers)
Mac OS X:  Core Audio
Windows:  directsound, winmm
Sound servers: pulseaudio, esound, arts

The defaults can be controlled by the end-user, as seen there: https://wiki.libsdl.org/FAQUsingSDL

**Dependencies:**
Save for libsdl all are optional depending on the features needed, judging from the gentoo ebuild. 
libsdl has no compulsory dependencies itself.

Palemoon isn't going to need any of the optional dependencies enabled specifically, since it will use SDL just for PCM audio. On free Unices the end user('s distro build) will choose; on OSX and Windows, the builds will simply need to enable what the platform provides.

**MSE**

>Media Source Extensions (MSE) is a W3C specification that allows JavaScript to send byte streams to media codecs within web browsers that support HTML5 video.

(From Wikipedia)
Thankfully this should have nothing to do with the topic at hand: audio PCM I/O.

--

**Alternatives:**
- ALmixer, an alternative to SDL_mixer based on OpenAL: https://bitbucket.org/ewing/almixer
- PortAudio, MIT-licensed and with Linux/OSX/Windows support: http://www.portaudio.com/ 


After researching this I found a short, good article (for a lib, not  an application, but still very relevant):
http://camlorn.net/posts/december2014/horror-of-audio-output.html

It sadly does not go into details for SDL (for his library), but notes how PortAudio has latency, and issues with >2ch audio related to channel ordering (but that was back in 2014). Good on the bugs side though?

**Comment by wolfbeast** [comment]
Thank you for the redundant MSE definition. It is directly related because the implementation will talk directly to cubeb and the likes and will require direct handling of audio channels.

**Comment by wolfbeast** [comment]
Alternatives: PortAudio is a no-go, it's too simple and won't satisfy the needs of multi-document, multi-channel, multi-frequency playback a web browser needs.
