### ISSUE TITLE
missing api...dll on 64bit win zip

### ISSUE THREAD

**Issue by grumpygeek** [MoonchildProductions/moebius#179]
64 bit zip file on Win8.1 won't start due to missing api-ms-win-crt-string-|1-1-0.dll  (github won't let me post image)

**Comment by scorpionsrk** [comment]
Hi

I am also facing the same problem - missing api-ms-win-crt-string-|1-1-0.dll  on WIN 8.1 64 bit

**Comment by scorpionsrk** [comment]
in fact I think there seems to be an issue with the portable version where it keeps asking for api-ms files

**Comment by wolfbeast** [comment]
Try using the installer instead of the zip file -- does that solve your issue?

**Comment by grumpygeek** [comment]
same error, no api files in installation folder like with Firefox (Otter has them too) I copied all 48 api-ms-win... files from Fx52ESR over to Basilisk and it now runs (didn't try just the one mentioned in the error)  but it sure would inspire more confidence if it ran first try.

**Comment by wolfbeast** [comment]
I did some research and apparently this is only an issue if you haven't installed all windows updates that are expected. Specifically, the Update for Universal C Runtime in Windows from Microsoft. (http://support.microsoft.com/kb/2999226). On Windows 8.1 you'd need to have installed the April 2014 update rollup for Windows RT 8.1, Windows 8.1, and Windows Server 2012 R2 (http://support.microsoft.com/kb/2919355)

The problem is caused by Visual Studio 2015 creating a dependency on the universal C runtime. I'll have a look to see if I can automatically bundle the required DLLs similar to what is already done with the CRT dlls, in the same vein as what Mozilla has done with Firefox.

**Comment by wolfbeast** [comment]
Looks like we need to set `WIN_UCRT_REDIST_DIR` similar to the CRT redist dir.

**Comment by wolfbeast** [comment]
> it sure would inspire more confidence if it ran first try

It sure would be nice if first releases are perfect in every way, indeed. But that's not being very realistic :)

On most systems, and certainly on all systems of our beta team and developers, this problem did not occur; so having this update installed is extremely common, and certainly common enough that _nobody_ ran into this before release.

**Comment by wolfbeast** [comment]
Confirmed that adding the extra export to mozconfig solves the issue. No code changes required; it's purely a build setup change that's needed.

**Comment by wolfbeast** [comment]
Issue resolved; close at M2 publish.
