### ISSUE TITLE
Basilisk location bar ceases to function after installing CTR

### ISSUE THREAD

**Issue by Telmesomething** [MoonchildProductions/moebius#193]
Downloaded Basilisk this morning with the intention to test it thoroughly, but after installing Classic Theme Restorer and importing a backup of my settings created in FF ESR 52.5 the location bar ceases to function. Typed URLs won't load and about:config cannot be accessed either. I even had to copy the verification URL for my email address after registering this morning into Firefox in order to complete the registration since Basilisk wouldn't load the page. 

Disabling CTR allows normal use.

**Comment by wolfbeast** [comment]
I'm sorry but there's no guarantee that all Firefox extensions will work on Basilisk without errors.
If there's a specific issue in the browser itself causing this, then I'll be more than happy to look into it, but it sounds like this is a CTR issue.

**Comment by JustOff** [comment]
> importing a backup of my settings created in FF ESR 52.5

In what way? FF ESR 52.5 settings are not generally compatible with Basilisk.

**Comment by Vangelis66** [comment]
> If there's a **specific issue in the browser itself** causing this, then I'll be more than happy to look into it, but it sounds like **this is a CTR issue**.

 As is often the case, the truth lies somewhere in the middle 😅 

 Yes, CTR was created and intended for Australis plagued Firefox versions (>=29.0a1); versions <=**44.0** are supported by CTR v**1.5.4beta9** (in the beta channel), but even recent (release/beta) CTR versions **do** still cater for Fx versions **45.0** - **56.0**; to be able to do that (and differentiate between 11 major Fx versions) CTR relies heavily on the reported app version (so as to apply the appropriate set of CSS files...). 

It would appear that Basilisk manifests itself to CTR as Fx 55.0 version, so CTR tries to apply to the Basilisk GUI CSS code written and meant for Mozilla Firefox 55.0; and that's where the breakage occurs 😞 
There's a specific CTR setting that's responsible for most of the breakage, including the symptoms described by the OP: 
`Location bar -> "Autocomplete Popup" tab -> Alternative appearance (classic)`
I suspect this setting existed in OP's Firefox profile, that he then imported (the CTR setting) to Basilisk, causing the basilisk GUI breakage. 

In any case, the developer of CTR (@Aris-t2) is already aware of the issue and has released [CTR v1.7.3.2beta1](https://addons.mozilla.org/en-US/firefox/addon/classicthemerestorer/versions/beta?page=1#version-1.7.3.2beta1) to rectify it: 

> [fix(es)]
> Basilisk & 'alt. autocomplete popup'
> Basilisk shows itself as Fx55, but uses Fx51-53 code for location bars popup

@JustOff wrote: 

> In what way? FF ESR 52.5 settings are not generally compatible with Basilisk.

If we're talking about complete profiles here, then, given that current Basilisk incarnation is a mix of Fx 51+52+53 code, I suspect many incompatibilities to be present between it and Fx ESR 52 (now at v52.5.0) but nothing fatal that would prevent the imported profile from running in Basilisk; an (experienced) user should be able to fix various broken things easily (via resetting prefs in about:config, downgrading extensions versions etc.). But **it's not recommended to migrate complete profiles from Firefox** (especially Fx >=53.0) into Basilisk; start from scratch, i.e. a clean profile, then selectively transfer bits from the Fx profile (mainly bookmarks & logins).

However, @Telmesomething wasn't talking about importing the full Fx 52.5.0 profile into Basilisk: 

> after installing Classic Theme Restorer and importing a backup of my settings created in FF ESR 52.5

The way I saw it he was referring to a native CTR feature, which is to export its many settings (the extension's, not the browser's) into a local file (.txt | .json), which can then be imported back into a second CTR installation (in the same or different supported browser), thus replicating the initial CTR setup in the second installation...

----------------------------------------------
Off topic: 

@wolfbeast 
I lament the decision to drop Vista support in Moebius/Vasilisk; this also means that eventually Pale Moon will also drop Vista with the migration to the UXP platform in the next months (start of 2018?). 
Pale Moon is my default browser now on Vista, but, FWIW, I am able to run Basilisk (x86) on Vista by hacking the subsystem string (6.1 -> 6.0); basic browsing works fine, however system codec support (Vista's WMF, i.e. h264/aac/mp3) is broken due to code changes by Mozilla in the codebase forked by Basilisk; is there a way you could restore Vista's WMF support in Basilisk the application (and not the platform Moebius in general) ? 
For all I know, I may have to use the [XPmod](http://www.msfn.org/board/topic/177125-my-build-of-new-moon-temp-name-aka-pale-moon-for-xp/?do=findComment&comment=1147132)...  
In any case, eternally grateful for Pale Moon (and now Basilisk) !

**Comment by Telmesomething** [comment]
> However, @Telmesomething wasn't talking about importing the full Fx 52.5.0 profile into Basilisk:

    after installing Classic Theme Restorer and importing a backup of my settings created in FF ESR 52.5

> The way I saw it he was referring to a native CTR feature, which is to export its many settings (the extension's, not the browser's) into a local file (.txt | .json), which can then be imported back into a second CTR installation (in the same or different supported browser), thus replicating the initial CTR setup in the second installation...

Yes, that's correct. It was only the CTR settings which I'd imported, not my FF ESR profile.

However, I'm pleased to report that the CTR 1.7.3.2 beta1 update has fixed the problem and I can now run Basilisk with CTR enabled. 

I'll install the other extensions I regularly use in Firefox and will update this thread if I come across any more issues concerning extensions. 

Thanks for your help guys.

**Comment by Aris-t2** [comment]
**@Basilisk devs**
Are you planning to update autocomplete popups code (urlbarBindings.xml/autocomplete.xml) to Firefox 55 or will it stay as is based on Fx51-53?

If I push CTR 1.7.3.2 beta1 to release and you update autocomplete code, this CTR feature will break again.

**Comment by wolfbeast** [comment]
@Aris-t2 We probably don't need to change the urlbar binding code for anything (do you know why Mozilla changed this, to begin with, making it incompatible?) because our fork's front-end won't get the rust/servo treatment, nor need any of the prep work Mozilla has done for it.
Basilisk's front-end code won't change much from this point forward except for bugfixes (no big changes/rearchitecturing/etc.) since our dev focus will be on the platform.

**Comment by Aris-t2** [comment]
@wolfbeast 

Mozilla changed urlbar code multiple times mostly to include new data collection methods and "suggestion" entries, nothing users really required.

I was asking, because Basilisk shows itself as Firefox 55 and some CTR options use different code for every Firefox version.

Good to hear you won't add new/modified bindings. The current code can stay then. I will will push a new CTR build to release soon.

**Comment by wolfbeast** [comment]
@Aris-t2 Ugh, yeah, more of those search partnerships, no doubt. No, no additional data collection or suggestion "features" are planned, at all. You should be good to push out to release, special-casing Basilisk as you have.

Basilisk's internal `appVersion` is a rough approximation of what it's "closest to" (if there is such a thing) in terms of Firefox compat, so there's unfortunately going to be a few things that won't match exactly; this front-end binding being one of them. It can't be helped when trying to cater to extensions for a different browser; it won't be a 1:1 match and can run into snags with extensions that have to check narrow version ranges like yours.

**Comment by Telmesomething** [comment]
Just a quick update after successfully installing 21 extensions today of which only one of them won't play ball. That's Video DownloadHelper [https://addons.mozilla.org/en-US/firefox/addon/video-downloadhelper/](url) for which there's no toolbar button to be seen anywhere. I tried uninstalling/reinstalling it again by dragging the XPI file from FF 52.5 ESR into Basilisk, but that didn't help either. 

I ran a search of their support forums and found a suggestion which dates from September 2016 which was to delete \ "action-button--b9db16a4-6edc-47ec-a1f4-b86292ed211d-vdh-tbbutton\ " and "browser.uiCustomization.state" from the Basilisk prefs.js but it didn't help. In fact it only served to remove all my precious CTR settings. Fortunately I'd taken the precaution of creating a copy of the prefs.js and was able to undo the damage. I tried it with just deleting the first pref, but it didn't change anything. 

I'm pleased to say though that Basilisk is a lot faster than FF 52.5 ESR and videos on the BBC News site snap open immediately. On FF  ESR I have to wait about 10 seconds for the throbber to disappear before any videos can be viewed. 

One observation if I may and that's with popups. My banking site uses them and although Basilisk displays the option to "Allow", there's no permanent way which can be configured from within that step such as the option to "Always allow popups from this site" which Firefox has. One has to manually add an exception to the popup blocker in the about:preferences#content menu. 

If you guys need any help with testing, drop me a line.

**Comment by mattatobin** [comment]
Is this resolved or what is the status on this whole thing...

**Comment by JustOff** [comment]
I think this has been resolved by [CTR 1.7.3.2](https://github.com/Aris-t2/ClassicThemeRestorer/commit/ec055e2b0d5055886157d91a721f7c93fe3a8add#diff-d9594edd70de85e03c04cdb7c6869178).

**Comment by wolfbeast** [comment]
Considered solved then
