### ISSUE TITLE
Problems with Firefox add-ons because of platformVersion

### ISSUE THREAD

**Issue by JustOff** [MoonchildProductions/moebius#198]
Many Firefox add-ons (for example [Add-ons Manager - Version Number](https://addons.mozilla.org/en-US/firefox/addon/amversionnumber/), [Dark Background and Light Text](https://addons.mozilla.org/en-US/firefox/addon/dark-background-light-text/)) rely on the `platformVersion` value, but Basilisk uses Goanna version there, so they work incorrectly or even refuse to run.

**Comment by wolfbeast** [comment]
Too bad.

**Comment by JustOff** [comment]
While I understand your `Wontfix` based on the fact that Basilisk is primarily intended for UXP development, this decision obviously contradicts `a potential replacement for Firefox to retain the use of Firefox Extensions`. I do not have a better solution, though ...

**Comment by galenhuntington** [comment]
I want to add that many Vimperator features do not work because it too relies on `platformVersion`.  See vimperator/vimperator-labs#814.  I noted a hack there to get it working.  This is a popular add-on, so that's something else to consider.  (But I don't have a good solution either.)

**Comment by wolfbeast** [comment]
I'll reconsider our approach for the re-forked platform, but the root cause remains that the Platform Version is not the Application Version. It's been a mistake by Mozilla to make those equal because Gecko != Firefox and Platform != Application. Extensions should be written accordingly keeping that in mind.
