### ISSUE TITLE
[suggestion] Potential crashes with an addons (Avast, uBlock Origin)

### ISSUE THREAD

**Issue by janekptacijarabaci** [MoonchildProductions/moebius#212]
See:
https://bugzilla.mozilla.org/show_bug.cgi?id=1347984

Follow up https://bugzilla.mozilla.org/show_bug.cgi?id=1346012 ?

However, I can not simulate it.

**Comment by mattatobin** [comment]
If you can't reproduce it how do you know it is applicable.. Also, why is there once again no info in the issue except a bugzilla link..

**Comment by janekptacijarabaci** [comment]
I may be wrong, so it's just a suggestion. The description is in the title. If it is not good, please close it.

**Comment by wolfbeast** [comment]
You didn't even check what this patch does, obviously, or you would have seen that it just adds a bunch of asserts to investigate what causes it, which we won't do anything with anyway (or do you plan to run a debug build to investigate?).
If you can't reproduce it, then the issue is probably not even present in our code base.

We need quality, not quantity, if we want this code base to go anywhere.

**Comment by janekptacijarabaci** [comment]
The main one is of course this:
https://github.com/MoonchildProductions/moebius/pull/213/files#diff-81b4a0d2b86d7886f15b8e6df4dc5180R811
and not debugging information.
