### ISSUE TITLE
Annihilate the Crash Reporter

### ISSUE THREAD

**Issue by mattatobin** [MoonchildProductions/moebius#22]
http://xref.palemoon.org/moebius-trunk/search?string=MOZ_CRASHREPORTER

**Comment by wolfbeast** [comment]
@trav90 should you remain assigned to this?

**Comment by trav90** [comment]
I'm still working on Pale Moon's media backend. I will eventually get to this, but if someone else would like to work on it by all means go for it!

**Comment by wolfbeast** [comment]
I'll rip it out. I feel like doing some work that doesn't require much advanced knowledge, and allows me to use the orbital cannon ;)

**Comment by wolfbeast** [comment]
Jeez. looks like in this code base it's a lot more complicated than I anticipated. So far I managed to not do anything extraordinary, but it still breaks the browser's front-end. For some reason.
I may have to leave it up to someone else after all.

**Comment by mattatobin** [comment]
Wait.. It has been tied into thr frontend code as well? Doesn't follow previous two times it was removed?

**Comment by wolfbeast** [comment]
Yes it's become almost as invasive as telemetry. I think part of it is because they are gathering a ton of information int he crash reports about the running system and also want to be able to report plugin crashes that don't take the rest of the browser down. So Front-end, IPC, etc. all is involved.

I managed to get the stuff mostly to behave though, step one is done, now it needs working backwards from stubs to callers, and getting rid of other related defines like `MOZ_CRASHREPORTER_NO_REPORT` and `MOZ_CRASHREPORTER_URL` occurrences and the likes.

**Comment by wolfbeast** [comment]
OK, so there's some serious weaving going on with the crashreporter because of e10s and crashed tabs and using crash reports for plugins as well. I have to be very very careful not to break our browser glue (which is why it broke the browser the first try).

**Comment by mattatobin** [comment]
There is still a MASSIVE amount of crash reporter in the codebase still..

**Comment by wolfbeast** [comment]
I'm aware. Why do you think I didn't close this?
What's been submitted is only the first part.
