### ISSUE TITLE
Basilisk disables my addons

### ISSUE THREAD

**Issue by CitoplasmaX** [MoonchildProductions/moebius#232]
I blocked them simultaneously when I'm doing anything and without warning and then in more information on the disabled addon I released the same following link https://blocked.cdn.mozilla.net/i988.html in all disabled addons that has nothing to do with Basilisk disables my addons.

**Comment by CitoplasmaX** [comment]
He has disabled Wappalyzer, Greasemonkey and Adblock Plus.

**Comment by wolfbeast** [comment]
Are you using the most current version of Basilisk? 2017-11-30 or 2017-12-01?

**Comment by CitoplasmaX** [comment]
2017.12.03

**Comment by wolfbeast** [comment]
Well, I don't know what commit that was built from, because the blocklist server was changed to our own, which most definitely does not include anything to disable those extensions specifically AFAIK.

**Comment by CitoplasmaX** [comment]
I have installed this addons manually, from original files downloaded from original webpages and mozilla. I believe that the problem could be on install addons manually.

**Comment by trav90** [comment]
It was built from the tip of the release branch. ABP is the only addon I have that you mentioned above but I have yet to see Basilisk disable it or any other addon.

**Comment by janekptacijarabaci** [comment]
I suppose: `Blocking...` = `This extension cannot be installed`

![cannot-be-installed](https://user-images.githubusercontent.com/2373486/33872077-a6ecd248-df15-11e7-9ebb-ccd72cb88259.png)

See also:
https://forum.palemoon.org/viewtopic.php?f=61&t=17664#p129317

**Comment by CitoplasmaX** [comment]
I am not using last version because, a time before i am using an ESR version of firefox (45).

**Comment by CitoplasmaX** [comment]
It is not a problem with last versions, and he disabled my addons a after a time while i am using him, this is, mainly i could use addons.

**Comment by CitoplasmaX** [comment]
![captura de pantalla de 2017-12-12 18 08 10](https://user-images.githubusercontent.com/30677099/33900761-894d8c94-df67-11e7-8b41-5c81a3f6475f.png)
![captura de pantalla de 2017-12-12 18 08 16](https://user-images.githubusercontent.com/30677099/33900762-89982c04-df67-11e7-972c-4520a18facfa.png)

**Comment by CitoplasmaX** [comment]
![captura de pantalla de 2017-12-12 18 12 44](https://user-images.githubusercontent.com/30677099/33900947-19c89b6a-df68-11e7-8f51-04d16c3b07fa.png)

**Comment by CitoplasmaX** [comment]
I have get ABP in normal after reinstall the addon some times.

**Comment by CitoplasmaX** [comment]
ABP again disabled...

![captura de pantalla de 2017-12-13 18 41 49](https://user-images.githubusercontent.com/30677099/33956101-801bfe2a-e035-11e7-81cc-9edd4e83995b.png)

**Comment by wolfbeast** [comment]
You must use the latest release of Basilisk.

**Comment by wolfbeast** [comment]
On a related note, this may in part also be related to there being 2 mechanisms in play now, one having been added on the quiet by Mozilla. This may depend on #247 to get properly resolved, although flipping the updates off through this C/S mechanism may also help for immediate alleviation:
Set `services.blocklist.update_enabled` to false. Despite its name it will NOT completely disable blocklist updates, just the updates through the "settings service mechanism".

**Comment by CitoplasmaX** [comment]
I am using last version of Basilist 

> 2017.12.03

> I am a GNU/Linux user.

I am not using last versions of addons by problems to install them.

**Comment by JustOff** [comment]
It's probably Linux-specific issue, see [here](https://forum.palemoon.org/viewtopic.php?p=130462#p130462).

**Comment by CitoplasmaX** [comment]
> On a related note, this may in part also be related to there being 2 mechanisms in play now, one having been added on the quiet by Mozilla. This may depend on #247 to get properly resolved, although flipping the updates off through this C/S mechanism may also help for immediate alleviation:
Set services.blocklist.update_enabled to false. Despite its name it will NOT completely disable blocklist updates, just the updates through the "settings service mechanism".

This is only a temporal solution, there is a deep problem that cause this in all extension disabled: https://blocked.cdn.mozilla.net/i988.html

The same link on whatever addon disabled.

**Comment by wolfbeast** [comment]
At least let me know if flipping the pref solves the issue. It's not a temporary solution if it's the Kinto service that causes this havoc, because it'll be disabled/removed in UXP.

**Comment by CitoplasmaX** [comment]
It is a temporary user, i am not real programmer but i believe that the browser believe that an addon is https://blocked.cdn.mozilla.net/i988.html this addon, is not a problem of "services.blocklist.update_enabled" because there is another option on mozilla about:config that say "extensions.blocklist.itemURL;https://blocklist.addons.mozilla.org/%LOCALE%/%APP%/blocked/%blockID%". The blockid is bad.

**Comment by dgoetz** [comment]
I flipped the preference mentioned and it again disabled one addon.

**Comment by CitoplasmaX** [comment]
change "extensions.blocklist.enabled" to false. i would prefer search blocklist and put false all about him.

**Comment by mattatobin** [comment]
Disabling the blocklist completely is NOT a solution. Stop recommending it. We are working on the problem.

**Comment by CitoplasmaX** [comment]
You are right, is only a temporary solution.

**Comment by jerome-diver** [comment]
same here for basilisk installed from source on archlinux.
update (simply download and untar files in place) break ability by default to access add-ons.

this link: [forum palemoon talking about this problem](https://forum.palemoon.org/viewtopic.php?p=130462#p130462)
Show that people-devs basilisk team who use Windows OS doesn't have this problem and are not motivate to find any solution on that for linux because they not use linux.

Quick solution ((but not fix the problem) is to disable extention.blocklists.enabled (need to be false)
for do that, address in the url editLine has to be: config:about (same as firefox) 
then go to line extention.blocklists.enabled and double click for read: false.

That resolve the access problem who make basilisk for devs or geeks unusable.

So actually, basilisk is not safe on linux, unstable for add-ons use, and it seems to be a problem who will be long to resolve due to Windows users only devs.

Good luck to the basilisk team and hope some of you would be interested to fix this specific linux issue (and maybe use linux OS... promise you will have fun on unix systems).

Happy new year all of you.

**Comment by wolfbeast** [comment]
@jerome-diver 

> Show that people-devs basilisk team who use Windows OS doesn't have this problem and are not motivate to find any solution on that for linux because they not use linux.

Please don't jump to conclusions. We are motivated plenty to get this resolved, and are working on it.

**Comment by jerome-diver** [comment]
@wolfbeast ho ok, sorry it was not for hurt you or Windows users or devs team. It was really not the target, and also that is why i edited my post, so i not understand why you paste that ? what is the idea in fact ? nevermind...

**As long as this is not resolved, the reality stays simple: we are now the 3 december 2018 and linux+basilisk ==> extention.blocklists.enabled to false.** 
If not, then no add-ons access possible easy and stable. That is a fact or not ? 
**It is not a GOOD solution, but actually, it seems to be the ONLY ONE who works** (all the time... not one hour). I don't lie when i said that.

Or... actually, is there an other one working solution i missed ? I would be happy to have a other one and no more recommend it. Really, what do you think ?
So there is not other solution the 3 december 2018. 

So understand that linux users who want to use add-ons with basilisk, it serve nothing to tell them to not do that because there is a kind of bug and there is some safety leakage ability. 
May i tell you that you should not use Windows for many safety and technical reasons (who exists really) ? no... i let you free to thinking and do what you want, i'm not your maste, i'm not the lawr; i'm thinking you are responsible of your acts, i can just be maximum for be informative, right ?
 i don't want to be pretentious or haughty, and i have nothing to prove. So just stay informative guys... do not become a kind of guru with 'don't do this, don't do that..." it's boring, all the time (every time).

You can tell them that for use basilisk under linux with add-ons, actually, they need to be exposed with any safety problems. People are not responsible, they no need a kind of nanny who tell them what to not do or what to think about, please... i think people are tired with that. We accept what we want, and we like to be informed. We know nothing is perfect and that's fine as long as it is the life (and by the way, you will think one day it is really safe... but it will be never safe really, every week there is kernel update... software and libraries update, for all OS, ok... it is more safe than before and less than tomorrow, and a kind of spirit conception around what is safe).

ok ladies and gentlemen, happy new year, thank you for your job and try to stay humble and informative as long as you can without provide a law about what we have to do or not. peace and freedom lover...

**Comment by wolfbeast** [comment]
Basilisk is development software. If it doesn't (yet) work on Linux, you are free to use something else; however suggesting that people open themselves up to known security risks as a "solution" is absolutely wrong, and no argumentation will change that fact.

Once more, we're working on it. Have some patience.

**Comment by wolfbeast** [comment]
Considering we're at a state where:
- Classic extensions install
- WebExtensions install
- No untoward signature warnings are given

... I'm considering this solved.

**Comment by trav90** [comment]
This was caused by compiler parallelization and will be fixed in the next Linux release of Basilisk.
