### ISSUE TITLE
? "Contrary to the "reducing entropy" approach ..."

### ISSUE THREAD

**Issue by equiplist** [MoonchildProductions/moebius#236]
>Contrary to the "reducing entropy" approach employed by some, our approach will be to make fingerprints unique every time, since it is more effective against practical tracking, with the added bonus that false data will bloat tracker databases.

I don't get it ... how can it be 'more effective'?

tag #59

**Comment by wolfbeast** [comment]
In a nutshell: If you present a new, unique identity every time, trackers will not be able to track you. They can record a datapoint for that unique identity, but it will not be repeated. Increasing entropy with the premise of creating a unique presence every time is therefore more efficient than reducing entropy.

The "minimal entropy" approach will require only one parameter to be unique to be able to track.
The "maximum random entropy" approach will require filtering out of every randomized parameter as well as an otherwise unique parameter to track. This reduces tracking options rapidly.
