### ISSUE TITLE
Add Media keys support to commands API

### ISSUE THREAD

**Issue by svnpenn** [MoonchildProductions/moebius#244]
These properties:

- MediaNextTrack
- MediaPlayPause
- MediaPrevTrack
- MediaStop

work with Firefox

http://developer.mozilla.org/Add-ons/WebExtensions/manifest.json/commands

**Comment by mattatobin** [comment]
I don't know who you are but you need to stop spamming every browser relayed repo and our issue tracker with WebExtension support requests cross linking them..

As for THIS request.. Our WebEx support in UXP is very much as-is and if you want this then Patches Welcome.. Otherwise please cool your jets.

**Comment by Sa-Ja-Di** [comment]
The main goal is here for sure not to develop webextensions technology further than some basic improvements if they are possible in a simple way - the goal here is to provide a future code base for Pale Moon.

You want advanced webextension support? Find someone who can do that, do it on your own or deliver tutorials and guides that it can be done in a "simple and effective not time consuming way".

**Comment by mattatobin** [comment]
The goal of UXP is to continue where Mozilla left off with the mozilla-style platform.. NOT just Pale Moon.

**Comment by mattatobin** [comment]
I am WONTFIXing this because it is spam.. If we do want to do some stuff with webextensions we can reopen this..
