### ISSUE TITLE
Compatibility Issues

### ISSUE THREAD

**Issue by nufrankz** [MoonchildProductions/moebius#245]
Hi! First of all, congratulations for keeping XUL Firefox alive. Many of us, Mozilla users, don't like the new transition to this only-WebExtension era of Firefox 57 and efforts like this are welcome.
Just two things:
- Want to Login to **Firefox Sync** but doesn't appear to work (show just blank screen with loading wheel)
- Want to **add Google as a Search Engine** but doesn't work (on the dropdown glass magnifier menu, when visiting google.com the option to make it a search provider doesn't appear)
- Want to **sync Bookmarks and Addons from actual Firefox** (the option doesn't appear when installing (as I remember or when installed)
Thank you and keep XUL alive 💪

**Comment by wolfbeast** [comment]
- Firefox Sync should be fixed with the next update (it's a useragent issue)
- Google Search doesn't offer an OpenSearch meta on its page -- that's not a browser issue. Google simply doesn't support this at this time.
- Syncing bookmarks should be possible once Firefox Sync (Firefox Accounts) is working. Syncing add-ons is not recommended because Basilisk is not Firefox. Please install (compatible version of) the add-ons you need. There is currently no working migrator from Firefox because Firefox's profile structure is constantly changing and there is no sane migration path. Blame Mozilla for that one.

**Comment by wolfbeast** [comment]
Closing because there's nothing actionable here that isn't already resolved.

**Comment by mattatobin** [comment]
If you want a Google Search Plugin you can go to http://addons.palemoon.org/search-plugins/ .. They will work in Basilisk or ANY open search compatible browser.
