### ISSUE TITLE
SSL_ERROR_NO_CYPHER_OVERLAP on some https sites

### ISSUE THREAD

**Issue by GauriSpears** [MoonchildProductions/moebius#259]
Basilisk 2017.12.01 32-bit
Windows 10 x64 v1703 (build 15063.540)
When I try to browse https://66.ru I get SSL_ERROR_NO_CYPHER_OVERLAP error. Firefox 52.3.0 opens the site successfully. I don't know whether there are other sites with similar behavior.

**Comment by GauriSpears** [comment]
UPD: the server uses TLS_DHE_RSA_WITH_AES_256_CBC_SHA, 256 bit, TLS 1.0

**Comment by wolfbeast** [comment]
Standard DHE (not EC) suites are disabled by default because of commonly weak DH keys, which is the case here, too.
The only non-DHE suite they support is Triple-DES which is also disabled because of the SWEET32 vulnerability. Firefox 52 will probably still allow this.

So it's correct: the cipher suites have no overlap with Basilisk (nor with Pale Moon for that matter that uses a similar security profile).

They need to:
1. Update their nginx to something more recent than 1.4.4
2. Use modern encryption cipher suites if they want to serve https
