### ISSUE TITLE
Port to Python 3?

### ISSUE THREAD

**Issue by awilfox** [MoonchildProductions/moebius#261]
Hi there,

I'm with the Adélie Linux distribution and since [Rust violates our packaging guidelines](https://adeliedev.blogspot.com/2017/11/official-stance-on-rust.html), we are very interested in this browser.  However, we only ship Python 3, not Python 2.

Would either porting the build system to Python 3, or porting it to run on either 2 or 3, be something that we would be able to work with you and merge in?  We have three people on our team, including myself, that have experience porting large codebases from 2 to 3, so we have the resources necessary to contribute.

**Comment by mattatobin** [comment]
The build system is a hybrid of a highly complex autotools and python system that is virtually stuck between the the the two.. It is crypic and quite fragile.

Do not underestimate it for a second.

Currently the plan is to replace it with an earlier incarnation to completely avoid mozconfigure. Once that is accomplished (if successful) we will be in a better position to evaluate python 3 compatibility.

Of course help with that would be amazing but I don't want anyone to lose any potental work because of the reversion of the build system. Also do note that we will need to maintain Python 2 compatibility.

I intend to begin the attempt shortly after the end of the year. I shall endever to keep you informed of that here.

Thank you for your offer and it shall be greatly appreciated!

**Comment by wolfbeast** [comment]
Putting this on hold for now because we need to clean up the build system to a slightly saner state first on UXP that doesn't rely so heavily on custom configuration scripts.
To better evaluate this, @awilfox do you have a reference available listing the breaking changes between Python 2 and 3, so we know what to expect in terms of amount of work and complexity required to make the build system compatible with Python 3?

**Comment by awilfox** [comment]
> Do not underestimate it for a second.

I actually have code in mozboot already :)  I have landed a few things in mozilla-central and I used to enjoy contributing, so I know exactly what I'm getting in to.

> do you have a reference available listing the breaking changes between Python 2 and 3

See the [Py Porting HOWTO](https://docs.python.org/3/howto/pyporting.html) on the official Python documentation site for more; especially see the heading "[Learn the differences between Python 2 & 3](https://docs.python.org/3/howto/pyporting.html#learn-the-differences-between-python-2-3)" for a link to a free e-book and cheat sheet.

**Comment by awilfox** [comment]
I would like to note here that I did at one point have mozilla-central building on Python 3, but the amount of code churn by that time (I believe 47 was trunk then) was making it impossible to keep up with.  The changes are fairly extensive, but also fairly simple and straightforward.  Mostly it is about Unicode/string safety, and a few changes in process execution.

**Comment by mattatobin** [comment]
You are kinda in luck assuming you have that previous effort as reference.. My goal is to use the build system of gecko/46 to replace ours which will completely avoid mozconfigure..

**Comment by wolfbeast** [comment]
If needed, re-issue on UXP
