### ISSUE TITLE
Use string "Preferences" instead of "Options" across all platforms

### ISSUE THREAD

**Issue by mattatobin** [MoonchildProductions/moebius#270]
Mozilla long ago with Firefox started using the word "Options" over the word "Preferences" but only on Windows.

This has caused long standing issues with people switching back and forth on term. Moving the menu item on Windows also compounded the issue.

Windows: Menu Bar > Tools > Options
Linux and Mac: Menu Bar > Edit > Preferences

Thus far and in Pale Moon we have maintained that separation of terms for exactly the same thing however on Basilisk it is compounded by in-content preferences being ALWAYS called in-content preferences and using an about URI of `about:preferences`.

For Basilisk I think we should resolve at LEAST the string discontinuity and prefer "Preferences" as the proper term for preferences across all Platforms.

As for the menu item location.. Really both menu item locations are valid. However, for Basilisk, it is early enough to move the menu item to it's historical location in the Edit Menu. If that is on the table.. Now would be the best time to do it because the menu bar in general is less likely to be used for Basilisk users so the impact of change will be much smaller.

----

Pale Moon on the other hand will likely have to maintain the status quo pretty much forever without a poll being conducted. But we can at least sort this on Basilisk for now. Perhaps for Pale Moon 28 we can ask the community and take the plunge there as well..

**Comment by JustOff** [comment]
Sorry, but I doubt that this makes any sense.

**Comment by wolfbeast** [comment]
Options, Settings and Preferences are generally used interchangably in software.
So, what makes more sense, then?

- Having this named differently and in a different location in the application depending on O.S., **OR**
- Having this named consistently and placed in a singular location?

**Comment by JustOff** [comment]
Honestly, I hate having controls in the left corner of windows under Ubuntu and I often miss the desired answer in Linux yes/no dialogues because the yes is on the right side. But I understand it's a kind of tradition I have to accept as is, and I think the same applies to options/settings/preferences. Probably potential benefits of such changes are not worth the extra controversy that may arise.

**Comment by wolfbeast** [comment]
@mattatobin for Pale Moon it isn't necessarily a status quo situation -- Pale Moon has always aimed to have a high level of O.S. integration, at least visually, in general following what is common in the O.S.; That's probably why we have Preferences in the Edit menu on Linux, which I really don't agree with, on a personal level (it has nothing to do with edit functions).

This issue is however filed on Basilisk. For Basilisk, I'm not entirely sure what our general aim should be since there is no precedent except the Mozilla one which is, honestly, all over the place. I have half a mind to just rename everything to "Settings" and putting it in one location (including the about: protocol choice of name becoming `about:settings`)

**Comment by mattatobin** [comment]
Whatever.. However changing the about address would break anything that may call upon it from an extension point of view.. It still doesn't resolve the fact that the word preferences is more prefered globally than settings or options.

They are called preferences always have been from libpref to greprefs to js pref() to nsIpref to nsIPerfBranch to pref/preferences in omnija to about:config to now about:preferences to what was unchanged on mac and linux..

ONLY a short sighted throwaway decision in Firefox development decided that it should be changed to Options on windows happened.. Most still call it preferences regardless..

I would prefer.. It is my preference that this either be aligned back or so NOTHING because making the situation worse by adding a third term will REALLY just make things worse.

**Comment by wolfbeast** [comment]
"Aligned back" in your preference would also mean putting it in "edit" which is very very wrong for Windows applications.

**Comment by mattatobin** [comment]
I am totally willing to accept the established location under tools given what has happened in the years since this has changed and even making tools the proper place across platforms since unlike the overwhelming and prevailing use of the term "Preferences" internal, external, and everywhere inbetween the physical location coupled with the Tools menu being the location of many other configuration menu items for extensions and components.

**Comment by wolfbeast** [comment]
WFM. I looked at the code and we can simplify and clean up the code as well, too, in that case. Half the time it's `itemnameUNIX` to special case *nix, and the other half it's `itemnameWin` to special-case windows, anyway, which is messy. Unifying all this will be a Good Thing™.

**Comment by wolfbeast** [comment]
Tested the windows side of things -- assuming *nix also works as-intended, but make a note to have a casual check with the next *nix build.

**Comment by mattatobin** [comment]
@trav90 Tag, you're it!

**Comment by trav90** [comment]
I've run into some build bustage (which I do not believe is caused by the changes made here). Investigating.

**Comment by trav90** [comment]
All good here on Linux! 👍
