### ISSUE TITLE
HTML - input - datetime

### ISSUE THREAD

**Issue by janekptacijarabaci** [MoonchildProductions/moebius#91]
See:

[Bug 888320](https://bugzilla.mozilla.org/show_bug.cgi?id=888320)
[meta] implement all time and date related input types

[Bug 1323674](https://bugzilla.mozilla.org/show_bug.cgi?id=1323674)
[meta] defects in date time input types

---

IMHO - The following bugfix will be required:

[Bug 1330699](https://bugzilla.mozilla.org/show_bug.cgi?id=1330699)
Implement the support for record<> in WebIDL Bindings

---

You edit the text as needed, please (I don't know what to write).

**Comment by wolfbeast** [comment]
Why would Implement the support for record<> in WebIDL Bindings be needed, according to you? (I didn't see it in your bulk PR so assuming it's not implemented)

**Comment by janekptacijarabaci** [comment]
It's not implemented. But it's needed for:
[bug 1341994](https://bugzilla.mozilla.org/show_bug.cgi?id=1341994) (https://hg.mozilla.org/mozilla-central/rev/75e73a2476b8#l8.17)
which blocks implementation of [bug 1337234](https://bugzilla.mozilla.org/show_bug.cgi?id=1337234)...
etc.

**Comment by wolfbeast** [comment]
Hah. You do realize that 1337234 is to cater to e10s, right? So that's N/A, and so is 1341994 (we'll never need that kind of IDL exposure of XBL bound functions because our (single) process will always have direct access permission to these functions.

Did you check whether the bugs you're porting are actually needed for non-e10s?? I'd rather not put a bunch of code bloat into the platform for something we are never going to use.

**Comment by janekptacijarabaci** [comment]
OK, I did not look at it in detail :-), thank you.
But [bug 1346085](https://bugzilla.mozilla.org/show_bug.cgi?id=1346085) and [bug 1347069](https://bugzilla.mozilla.org/show_bug.cgi?id=1347069), e.g.
(I'm not dealing with it now)

**Comment by wolfbeast** [comment]
I don't think anyone cares if it's not a reason to complain.
